 /** @file userModelDriverController.h 
  *
  * Version 1.0
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  *
  * \defgroup DREAM_cognitiveComponent userModelDriver
  * 
  * Main class with code, use the yarpInterface class to communicate with the other components.
  * 
  * \section lib_sec Libraries
  *
  * None
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \author 
  * 
  * <James Kennedy>, <Plymouth University>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */

/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  James Kennedy, Plymouth University 
 * Email:   james.kennedy@plymouth.ac.uk 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */

 
 /* 
  * Audit Trail
  * -----------
  * 18/08/2016 Version 1.0: ... (James Kennedy)
  */ 
 
#ifndef USERMODELDRIVERCONTROLLER
#define USERMODELDRIVERCONTROLLER

#include <iostream>
#include <string>
#include <vector>
#include <windows.h>
#include "userListLibrary.h"
#include "userDataLibrary.h"

#define BOOST_FILESYSTEM_VERSION 3
#define BOOST_FILESYSTEM_NO_DEPRECATED 
#include <boost/filesystem.hpp>

class UserModelDriverYarpInterface;

class UserModelDriverController{
private:
	UserModelDriverYarpInterface* _yarpInterface;

	bool _bTest;
	int _iLastInteractionID;
	int _iLastScriptID;
    std::string _sLastSessionPartner;
    int _iLastSessionID;
public:
	/* class methods */
	UserModelDriverController(UserModelDriverYarpInterface *yarpInterface);
	
	void test();
	void sendNewID(int iNewID);
	void sendNewInteraction(user_interaction_data_t newInteraction);
	void receiveUserData(UserDataLibrary userDataIn);
	void simulateInteractionForTest();
	std::string getTimeStamp();
    void simulateUpdateForTest();
};

#endif
