 /** @file assessChildPerformanceYarpInterface.h 
  *
  * Version 1.0
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  * \defgroup DREAM_assessChildPerformance assessChildPerformance
  * 
  * Class used to provided a simpler interface between the main code and the YARP layer.
  * Provide an output function sending data for each port, and an input function called 
  * when a message is received on a port.
  * 
  * \section lib_sec Libraries
  *
  * - YARP.
  *
  * \section portsc_sec Ports Created
  *
  * <b>Port types </b>
  *
  *	BufferedPort<VectorOf<int> >		identifyVoiceIn;
  *	BufferedPort<VectorOf<double> >		getEyeGazeIn;
  *	BufferedPort<VectorOf<double> >		getBodyPoseIn;
  *	BufferedPort<VectorOf<double> >		identifyTrajectoryIn;
  *	BufferedPort<VectorOf<int> >		getInterventionStatusIn;
  *	BufferedPort<VectorOf<int> >		interactionEventIn;
  *	BufferedPort<VectorOf<double> >		getChildBehaviourOut;
  *	BufferedPort<VectorOf<int> >		identifyTrajectoryOut;
  *	BufferedPort<VectorOf<double> >		getChildPerformanceOut;
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \author 
  * 
  * <Serge Thill>, <University of Skövde>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */

/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  Serge Thill, University of Skövde 
 * Email:   serge.thill@his.se 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */
 
 /* 
  * Audit Trail
  * -----------
  * 08/11/2016 Version 1.0: ... (Serge Thill)
  */ 
 
#ifndef ASSESSCHILDPERFORMANCEYARPINTERFACE
#define ASSESSCHILDPERFORMANCEYARPINTERFACE

#include <iostream>
#include <string>
#include <vector>

#include <yarp/sig/all.h>
#include <yarp/os/all.h>
#include <yarp/os/RFModule.h>
#include <yarp/os/Network.h>
#include <yarp/os/Thread.h>

using namespace yarp::os; 
using namespace yarp::sig;

class AssessChildPerformanceThread;
class AssessChildPerformanceController;

class AssessChildPerformanceYarpInterface{
private:
	AssessChildPerformanceThread* _yarpThread;
	AssessChildPerformanceController* _controller;

	double _dblExpected;
public:
	/* class methods */
	AssessChildPerformanceYarpInterface();
    void init(AssessChildPerformanceThread* yarpThread, AssessChildPerformanceController* controller);
	void getFromIdentifyVoice(VectorOf<int> data);
	void getFromGetEyeGaze(VectorOf<double> data);
	void getFromGetBodyPose(VectorOf<double> data);
	void getFromIdentifyTrajectory(VectorOf<double> data);
	void getFromGetInterventionStatus(VectorOf<int> data);
	void getFromInteractionEvent(VectorOf<int> data);
	void sendToGetChildBehaviour(VectorOf<double> data);
	void sendToIdentifyTrajectory(int behaviour, int window);
	void sendToGetChildPerformance(double data);
};

#endif
