 /** @file sandtrayServer.h 
  *
  * Version 1.0
  * 
  * 22/06/2016
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  * \section component_description Component Description
  *
  * Functionally, the component performs one channel of communication with the sandtray game
  * 
  * \section lib_sec Libraries
  *
  * - YARP.
  *
  * \section parameters_sec Parameters
  * 
  * <b>Command-line Parameters </b> 
  * 
  * The following key-value pairs can be specified as command-line parameters 
  * by prefixing \c -- to the key e.g. \c --from file.ini. 
  * The value part can be changed to suit your needs; the default values are 
  * shown below. 
  *
  * - \c from \c sandtrayServer.ini 
  *    - specifies the configuration file
  *
  * - \c context \c component/sandtrayServer/configuration
  *   - specifies the sub-path from \c $DREAM_ROOT/release
  *   to the configuration file
  *
  * - \c name \c sandtrayServer   
  *   - specifies the name of the component (used to form the stem of component port names)  
  *
  *
  * <b>Configuration File Parameters </b>
  *
  * The following key-value pairs can be specified as parameters in the configuration file 
  * (they can also be specified as command-line parameters if you so wish). 
  * The value part can be changed to suit your needs; the default values are shown below. 
  * 
  * Key | Value
  * :-- | :----  
  * _sandtrayCommandIn | /sandtrayServer/sandtrayCommand:i
  *
  * - description
  *   
  * Key | Value
  * :-- | :---- 
  * _sandtrayReturnOut | /sandtrayServer/sandtrayReturn:o    
  *
  * - description
  *
  * \section portsa_sec Ports Accessed
  * 
  * - None
  *                      
  * \section portsc_sec Ports Created
  *
  * <b>Input ports</b>
  *
  *  - \c /sandtrayServer
  *
  *  - \c /sandtrayServer/sandtrayCommand:i
  *
  * <b>Output ports</b>
  *
  *  - \c /sandtrayServer
  *
  *  - \c /sandtrayServer/sandtrayReturn:o
  *
  * <b>Port types </b>
  *
  * The functional specification only names the ports to be used to communicate with the component 
  * but doesn't say anything about the data transmitted on the ports. This is defined by the following code. 
  *
  * \c BufferedPort<Bottle>		sandtrayCommandIn; 
  * \c BufferedPort<Bottle>		sandtrayReturnOut; 
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \section conf_file_sec Configuration Files
  *
  * \c sandtrayServer.ini   
  *
  * \section example_sec Example Instantiation of the Component
  * 
  * <tt>sandtrayServer --name sandtrayServer --context sandtrayServer/config --from sandtrayServer.ini </tt>
  *
  * \author 
  * 
  * <James Kennedy>, <Plymouth University>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */
  
/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  James Kennedy, Plymouth University 
 * Email:   james.kennedy@plymouth.ac.uk 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */
  
 /* 
  * Audit Trail
  * -----------
  * 22/06/2016 Version 1.0: ... (James Kennedy)
  */ 
 
#ifndef SANDTRAYSERVER
#define SANDTRAYSERVER

#include <iostream>
#include <string>
#include <vector>

#include <yarp/sig/all.h>
#include <yarp/os/all.h>
#include <yarp/os/RFModule.h>
#include <yarp/os/Network.h>
#include <yarp/os/Thread.h>

using namespace yarp::os; 
using namespace yarp::sig;

class SandtrayServerYarpInterface;
class SandtrayServerController;

class SandtrayCommandInAnalyser : public BufferedPort<Bottle>{
   virtual void onRead(Bottle& sandtrayCommandInData);
   SandtrayServerYarpInterface *_sandtrayServerYarpInterface;
public:
   void setSandtrayServer(SandtrayServerYarpInterface* yarpInterface);
};


class SandtrayServerThread : public yarp::os::Thread{
private:
	/* class variables */
	yarp::os::BufferedPort<Bottle>* _sandtrayCommandIn;
	yarp::os::BufferedPort<Bottle>* _sandtrayReturnOut;
	SandtrayServerYarpInterface* _yarpInterface;
	SandtrayCommandInAnalyser *_sandtrayCommandInAnalyser;
	
public:
	/* class methods */
	SandtrayServerThread(BufferedPort<Bottle>* sandtrayCommandIn, BufferedPort<Bottle>* sandtrayReturnOut);
	void setYarpInterface(SandtrayServerYarpInterface* yarpInterface);
	bool threadInit();
	void threadRelease();
	void sendToSandtrayReturn(Bottle data);
	void run();
};

class SandtrayServer : public yarp::os::RFModule{
private:
	/* module parameters */
	std::string _moduleName;
	std::string _sandtrayCommandInName;
	std::string _sandtrayReturnOutName;
	std::string _handlerPortName;

	/* class variables */
	yarp::os::BufferedPort<Bottle> _sandtrayCommandIn;
	yarp::os::BufferedPort<Bottle> _sandtrayReturnOut;
	yarp::os::Port _handlerPort;

	/* pointer to a new thread */
	SandtrayServerThread* _sandtrayServerThread;
	SandtrayServerController* _sandtrayServerController;
	SandtrayServerYarpInterface* _sandtrayServerYarpInterface;
public:
	/* class methods */
	bool configure(yarp::os::ResourceFinder &rf);
	bool interruptModule();
	bool close();
	bool respond(const yarp::os::Bottle& command, Bottle& reply);
	double getPeriod();
	bool updateModule();
};

#endif
