 /** @file userModel.h 
  *
  * Version 1.0
  * 
  * 13/06/2016
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  * \section component_description Component Description
  *
  * Functionally, the component reads user model XML files and parses them into a data type
  * that can be shared between components (namely the SMS and GUI)
  * 
  * \section lib_sec Libraries
  *
  * - YARP.
  *
  * \section parameters_sec Parameters
  * 
  * <b>Command-line Parameters </b> 
  * 
  * The following key-value pairs can be specified as command-line parameters 
  * by prefixing \c -- to the key e.g. \c --from file.ini. 
  * The value part can be changed to suit your needs; the default values are 
  * shown below. 
  *
  * - \c from \c userModel.ini 
  *    - specifies the configuration file
  *
  * - \c context \c component/userModel/configuration
  *   - specifies the sub-path from \c $DREAM_ROOT/release
  *   to the configuration file
  *
  * - \c name \c userModel   
  *   - specifies the name of the component (used to form the stem of component port names)  
  *
  *
  * <b>Configuration File Parameters </b>
  *
  * The following key-value pairs can be specified as parameters in the configuration file 
  * (they can also be specified as command-line parameters if you so wish). 
  * The value part can be changed to suit your needs; the default values are shown below. 
  * 
  * Key | Value
  * :-- | :----  
  * _userIDIn | /userModel/userID:i
  * _updatedDataIn | /userModel/updatedData:i
  *
  * - description
  *   
  * Key | Value
  * :-- | :---- 
  * _userDataOut | /userModel/userData:o    
  *
  * - description
  *
  * \section portsa_sec Ports Accessed
  * 
  * - None
  *                      
  * \section portsc_sec Ports Created
  *
  * <b>Input ports</b>
  *
  *  - \c /userModel
  *
  *  - \c /userModel/userID:i
  *  - \c /userModel/updatedData:i
  *
  * <b>Output ports</b>
  *
  *  - \c /userModel
  *
  *  - \c /userModel/userData:o
  *
  * <b>Port types </b>
  *
  * The functional specification only names the ports to be used to communicate with the component 
  * but doesn't say anything about the data transmitted on the ports. This is defined by the following code. 
  *
  * \c BufferedPort<VectorOf<int>>		userIDIn; 
  * \c BufferedPort<Bottle>		updatedDataIn; 
  * \c BufferedPort<Bottle>		userDataOut; 
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \section conf_file_sec Configuration Files
  *
  * \c userModel.ini   
  *
  * \section example_sec Example Instantiation of the Component
  * 
  * <tt>userModel --name userModel --context userModel/config --from userModel.ini </tt>
  *
  * \author 
  * 
  * <James Kennedy>, <Plymouth University>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */
  
/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  James Kennedy, Plymouth University 
 * Email:   james.kennedy@plymouth.ac.uk 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */
  
 /* 
  * Audit Trail
  * -----------
  * 13/06/2016 Version 1.0: ... (James Kennedy)
  */ 
 
#ifndef USERMODEL
#define USERMODEL

#include <iostream>
#include <string>
#include <vector>

#include <yarp/sig/all.h>
#include <yarp/os/all.h>
#include <yarp/os/RFModule.h>
#include <yarp/os/Network.h>
#include <yarp/os/Thread.h>

using namespace yarp::os; 
using namespace yarp::sig;

class UserModelYarpInterface;
class UserModelController;

class UserIDInAnalyser : public BufferedPort<VectorOf<int>>{
   virtual void onRead(VectorOf<int>& userIDInData);
   UserModelYarpInterface *_userModelYarpInterface;
public:
   void setUserModel(UserModelYarpInterface* yarpInterface);
};

class UpdatedDataInAnalyser : public BufferedPort<Bottle>{
   virtual void onRead(Bottle& updatedDataInData);
   UserModelYarpInterface *_userModelYarpInterface;
public:
   void setUserModel(UserModelYarpInterface* yarpInterface);
};



class UserModelThread : public yarp::os::Thread{
private:
	/* class variables */
	yarp::os::BufferedPort<VectorOf<int>>* _userIDIn;
	yarp::os::BufferedPort<Bottle>* _updatedDataIn;
	yarp::os::BufferedPort<Bottle>* _userDataOut;
	UserModelYarpInterface* _yarpInterface;
	UserIDInAnalyser *_userIDInAnalyser;
	UpdatedDataInAnalyser *_updatedDataInAnalyser;
	
public:
	/* class methods */
	UserModelThread(BufferedPort<VectorOf<int>>* userIDIn, BufferedPort<Bottle>* updatedDataIn, BufferedPort<Bottle>* userDataOut);
   void setYarpInterface(UserModelYarpInterface* yarpInterface);
	bool threadInit();
	void threadRelease();
	void sendToUserData(Bottle data);
	void run();
};

class UserModel : public yarp::os::RFModule{
private:
	/* module parameters */
	std::string _moduleName;
	std::string _userIDInName;
	std::string _updatedDataInName;
	std::string _userDataOutName;
	std::string _handlerPortName;
	std::string _userIni;

	/* class variables */
	yarp::os::BufferedPort<VectorOf<int>> _userIDIn;
	yarp::os::BufferedPort<Bottle> _updatedDataIn;
	yarp::os::BufferedPort<Bottle> _userDataOut;
	yarp::os::Port _handlerPort;

	/* pointer to a new thread */
	UserModelThread* _userModelThread;
   UserModelController* _userModelController;
   UserModelYarpInterface* _userModelYarpInterface;
public:
	/* class methods */
	bool configure(yarp::os::ResourceFinder &rf);
	bool interruptModule();
	bool close();
	bool respond(const yarp::os::Bottle& command, Bottle& reply);
	double getPeriod();
	bool updateModule();
};

#endif
