 /** @file assessChildEngagementController.h 
  *
  * Version 1.0
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  *
  * \defgroup DREAM_assessChildEngagement assessChildEngagement
  * 
  * Main class with code, use the yarpInterface class to communicate with the other components.
  * 
  * \section lib_sec Libraries
  *
  * None
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \author 
  * 
  * <Serge Thill>, <University of Skövde>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */

/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  Serge Thill, University of Skövde 
 * Email:   serge.thill@his.se 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */
 
 /* 
  * Audit Trail
  * -----------
  * 08/11/2016 Version 1.0: ... (Serge Thill)
  */ 
 
#ifndef ASSESSCHILDENGAGEMENTCONTROLLER
#define ASSESSCHILDENGAGEMENTCONTROLLER

#include <iostream>
#include <string>
#include <vector>

class AssessChildEngagementYarpInterface;

class AssessChildEngagementController{
private:
	AssessChildEngagementYarpInterface* _yarpInterface;

  int _smile;
  int _gaze;
  int _body;

  double _first_t;
  double _second_t;

  int _t_thr;


public:
	/* class methods */
	AssessChildEngagementController(AssessChildEngagementYarpInterface *yarpInterface);
  

  void gotSmile(int data);
  void gotBody(double data);
  void gotGaze(int data);

  double getEngagement();
  void reset_state();


  void evalGaze(int data); 
  void evalBody(double data);
  void evalSmile(int data);

  double body_thr;
  double centre_pos;

};

#endif
