 /** @file systemGUIDriver.h 
  *
  * Version 1.0
  * 
  * 14/11/2016
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  * \section component_description Component Description
  *
  * Functionally, the component  does ...xyz...
  * 
  * \section lib_sec Libraries
  *
  * - YARP.
  *
  * \section parameters_sec Parameters
  * 
  * <b>Command-line Parameters </b> 
  * 
  * The following key-value pairs can be specified as command-line parameters 
  * by prefixing \c -- to the key e.g. \c --from file.ini. 
  * The value part can be changed to suit your needs; the default values are 
  * shown below. 
  *
  * - \c from \c systemGUIDriver.ini 
  *    - specifies the configuration file
  *
  * - \c context \c component/systemGUIDriver/configuration
  *   - specifies the sub-path from \c $DREAM_ROOT/release
  *   to the configuration file
  *
  * - \c name \c systemGUIDriver   
  *   - specifies the name of the component (used to form the stem of component port names)  
  *
  *
  * <b>Configuration File Parameters </b>
  *
  * The following key-value pairs can be specified as parameters in the configuration file 
  * (they can also be specified as command-line parameters if you so wish). 
  * The value part can be changed to suit your needs; the default values are shown below. 
  * 
  * Key | Value
  * :-- | :----  
  * _selectedBySupervisorIn | /systemGUIDriver/selectedBySupervisor:i
  * _therapistCommandIn | /systemGUIDriver/therapistCommand:i
  * _userIDIn | /systemGUIDriver/userID:i
  *
  * - description
  *   
  * Key | Value
  * :-- | :---- 
  * _getChildBehaviourOut | /systemGUIDriver/getChildBehaviour:o    
  * _getChildPerformanceOut | /systemGUIDriver/getChildPerformance:o     
  * _proposedToSupervisorOut | /systemGUIDriver/proposedToSupervisor:o    
  * _smsSummaryOut | /systemGUIDriver/smsSummary:o     
  *
  * - description
  *
  * \section portsa_sec Ports Accessed
  * 
  * - None
  *                      
  * \section portsc_sec Ports Created
  *
  * <b>Input ports</b>
  *
  *  - \c /systemGUIDriver
  *
  *  - \c /systemGUIDriver/selectedBySupervisor:i
  *  - \c /systemGUIDriver/therapistCommand:i
  *  - \c /systemGUIDriver/userID:i
  *
  * <b>Output ports</b>
  *
  *  - \c /systemGUIDriver
  *
  *  - \c /systemGUIDriver/getChildBehaviour:o
  *  - \c /systemGUIDriver/getChildPerformance:o
  *  - \c /systemGUIDriver/proposedToSupervisor:o
  *  - \c /systemGUIDriver/smsSummary:o
  *
  * <b>Port types </b>
  *
  * The functional specification only names the ports to be used to communicate with the component 
  * but doesn't say anything about the data transmitted on the ports. This is defined by the following code. 
  *
  * \c BufferedPort<Bottle>		selectedBySupervisorIn; 
  * \c BufferedPort<Bottle>		therapistCommandIn; 
  * \c BufferedPort<VectorOf<int>>		userIDIn; 
  * \c BufferedPort<VectorOf<double>>		getChildBehaviourOut; 
  * \c BufferedPort<VectorOf<double>>		getChildPerformanceOut; 
  * \c BufferedPort<Bottle>		proposedToSupervisorOut; 
  * \c BufferedPort<Bottle>		smsSummaryOut; 
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \section conf_file_sec Configuration Files
  *
  * \c systemGUIDriver.ini   
  *
  * \section example_sec Example Instantiation of the Component
  * 
  * <tt>systemGUIDriver --name systemGUIDriver --context systemGUIDriver/config --from systemGUIDriver.ini </tt>
  *
  * \author 
  * 
  * <Hoang-Long Cao>, <Vrije Universiteit Brussel>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */
  
/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  Hoang-Long Cao, Vrije Universiteit Brussel 
 * Email:   hoang.long.cao@vub.ac.be 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */

  
 /* 
  * Audit Trail
  * -----------
  * 14/11/2016 Version 1.0: ... (Hoang-Long Cao)
  */ 
 
#ifndef SYSTEMGUIDRIVER
#define SYSTEMGUIDRIVER

#include <iostream>
#include <string>
#include <vector>

#include <yarp/sig/all.h>
#include <yarp/os/all.h>
#include <yarp/os/RFModule.h>
#include <yarp/os/Network.h>
#include <yarp/os/Thread.h>

using namespace yarp::os; 
using namespace yarp::sig;

class SystemGUIDriverYarpInterface;
class SystemGUIDriverController;

class SelectedBySupervisorInAnalyser : public BufferedPort<Bottle>{
   virtual void onRead(Bottle& selectedBySupervisorInData);
   SystemGUIDriverYarpInterface *_systemGUIDriverYarpInterface;
public:
   void setSystemGUIDriver(SystemGUIDriverYarpInterface* yarpInterface);
};

class TherapistCommandInAnalyser : public BufferedPort<Bottle>{
   virtual void onRead(Bottle& therapistCommandInData);
   SystemGUIDriverYarpInterface *_systemGUIDriverYarpInterface;
public:
   void setSystemGUIDriver(SystemGUIDriverYarpInterface* yarpInterface);
};

class UserIDInAnalyser : public BufferedPort<VectorOf<int>>{
   virtual void onRead(VectorOf<int>& userIDInData);
   SystemGUIDriverYarpInterface *_systemGUIDriverYarpInterface;
public:
   void setSystemGUIDriver(SystemGUIDriverYarpInterface* yarpInterface);
};


class SystemGUIDriverThread : public yarp::os::Thread{
private:
	/* class variables */
	yarp::os::BufferedPort<Bottle>* _selectedBySupervisorIn;
	yarp::os::BufferedPort<Bottle>* _therapistCommandIn;
	yarp::os::BufferedPort<VectorOf<int>>* _userIDIn;
	yarp::os::BufferedPort<VectorOf<double>>* _getChildBehaviourOut;
	yarp::os::BufferedPort<VectorOf<double>>* _getChildPerformanceOut;
	yarp::os::BufferedPort<Bottle>* _proposedToSupervisorOut;
	yarp::os::BufferedPort<Bottle>* _smsSummaryOut;
	SystemGUIDriverYarpInterface* _yarpInterface;
	SelectedBySupervisorInAnalyser *_selectedBySupervisorInAnalyser;
	TherapistCommandInAnalyser *_therapistCommandInAnalyser;
	UserIDInAnalyser *_userIDInAnalyser;
	
public:
	/* class methods */
	SystemGUIDriverThread(BufferedPort<Bottle>* selectedBySupervisorIn, BufferedPort<Bottle>* therapistCommandIn, BufferedPort<VectorOf<int>>* userIDIn, BufferedPort<VectorOf<double>>* getChildBehaviourOut, BufferedPort<VectorOf<double>>* getChildPerformanceOut, BufferedPort<Bottle>* proposedToSupervisorOut, BufferedPort<Bottle>* smsSummaryOut);
   void setYarpInterface(SystemGUIDriverYarpInterface* yarpInterface);
	bool threadInit();
	void threadRelease();
	void sendToGetChildBehaviour(VectorOf<double> data);
	void sendToGetChildPerformance(VectorOf<double> data);
	void sendToProposedToSupervisor(Bottle data);
	void sendToSmsSummary(Bottle data);
	void run();
};

class SystemGUIDriver : public yarp::os::RFModule{
private:
	/* module parameters */
	std::string _moduleName;
	std::string _selectedBySupervisorInName;
	std::string _therapistCommandInName;
	std::string _userIDInName;
	std::string _getChildBehaviourOutName;
	std::string _getChildPerformanceOutName;
	std::string _proposedToSupervisorOutName;
	std::string _smsSummaryOutName;
	std::string _handlerPortName;

	/* class variables */
	yarp::os::BufferedPort<Bottle> _selectedBySupervisorIn;
	yarp::os::BufferedPort<Bottle> _therapistCommandIn;
	yarp::os::BufferedPort<VectorOf<int>> _userIDIn;
	yarp::os::BufferedPort<VectorOf<double>> _getChildBehaviourOut;
	yarp::os::BufferedPort<VectorOf<double>> _getChildPerformanceOut;
	yarp::os::BufferedPort<Bottle> _proposedToSupervisorOut;
	yarp::os::BufferedPort<Bottle> _smsSummaryOut;
	yarp::os::Port _handlerPort;

	/* pointer to a new thread */
	SystemGUIDriverThread* _systemGUIDriverThread;
    SystemGUIDriverController* _systemGUIDriverController;
    SystemGUIDriverYarpInterface* _systemGUIDriverYarpInterface;
public:
	/* class methods */
	bool configure(yarp::os::ResourceFinder &rf);
	bool interruptModule();
	bool close();
	bool respond(const yarp::os::Bottle& command, Bottle& reply);
	double getPeriod();
	bool updateModule();
};

#endif
