 /** @file sandtrayEvent.h 
  *
  * Version 1.0
  * 
  * 29/06/2016
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  * \section component_description Component Description
  *
  * Functionally, the component receives data from the sandtray and broadcasts it
  * 
  * \section lib_sec Libraries
  *
  * - YARP.
  *
  * \section parameters_sec Parameters
  * 
  * <b>Command-line Parameters </b> 
  * 
  * The following key-value pairs can be specified as command-line parameters 
  * by prefixing \c -- to the key e.g. \c --from file.ini. 
  * The value part can be changed to suit your needs; the default values are 
  * shown below. 
  *
  * - \c from \c sandtrayEvent.ini 
  *    - specifies the configuration file
  *
  * - \c context \c component/sandtrayEvent/configuration
  *   - specifies the sub-path from \c $DREAM_ROOT/release
  *   to the configuration file
  *
  * - \c name \c sandtrayEvent   
  *   - specifies the name of the component (used to form the stem of component port names)  
  *
  *
  * <b>Configuration File Parameters </b>
  *
  * The following key-value pairs can be specified as parameters in the configuration file 
  * (they can also be specified as command-line parameters if you so wish). 
  * The value part can be changed to suit your needs; the default values are shown below. 
  * 
  * Key | Value
  * :-- | :----  
  *
  * - description
  *   
  * Key | Value
  * :-- | :---- 
  * _sandtrayEventOut | /sandtrayEvent/sandtrayEvent:o    
  *
  * - description
  *
  * \section portsa_sec Ports Accessed
  * 
  * - None
  *                      
  * \section portsc_sec Ports Created
  *
  * <b>Input ports</b>
  *
  *  - \c /sandtrayEvent
  *
  *
  * <b>Output ports</b>
  *
  *  - \c /sandtrayEvent
  *
  *  - \c /sandtrayEvent/sandtrayEvent:o
  *
  * <b>Port types </b>
  *
  * The functional specification only names the ports to be used to communicate with the component 
  * but doesn't say anything about the data transmitted on the ports. This is defined by the following code. 
  *
  * \c BufferedPort<Bottle>		sandtrayEventOut; 
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \section conf_file_sec Configuration Files
  *
  * \c sandtrayEvent.ini   
  *
  * \section example_sec Example Instantiation of the Component
  * 
  * <tt>sandtrayEvent --name sandtrayEvent --context sandtrayEvent/config --from sandtrayEvent.ini </tt>
  *
  * \author 
  * 
  * <James Kennedy>, <Plymouth University>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */
  
/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  James Kennedy, Plymouth University 
 * Email:   james.kennedy@plymouth.ac.uk 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */
  
 /* 
  * Audit Trail
  * -----------
  * 29/06/2016 Version 1.0: ... (James Kennedy)
  */ 
 
#ifndef SANDTRAYEVENT
#define SANDTRAYEVENT

#include <iostream>
#include <string>
#include <vector>

#include <yarp/sig/all.h>
#include <yarp/os/all.h>
#include <yarp/os/RFModule.h>
#include <yarp/os/Network.h>
#include <yarp/os/Thread.h>

using namespace yarp::os; 
using namespace yarp::sig;

class SandtrayEventYarpInterface;
class SandtrayEventController;


class SandtrayEventThread : public yarp::os::Thread{
private:
	/* class variables */
	yarp::os::BufferedPort<Bottle>* _sandtrayEventOut;
	SandtrayEventYarpInterface* _yarpInterface;
	
public:
	/* class methods */
	SandtrayEventThread(BufferedPort<Bottle>* sandtrayEventOut);
	void setYarpInterface(SandtrayEventYarpInterface* yarpInterface);
	bool threadInit();
	void threadRelease();
	void sendToSandtrayEvent(Bottle data);
	void run();
};

class SandtrayEvent : public yarp::os::RFModule{
private:
	/* module parameters */
	std::string _moduleName;
	std::string _sandtrayEventOutName;
	std::string _handlerPortName;

	/* class variables */
	yarp::os::BufferedPort<Bottle> _sandtrayEventOut;
	yarp::os::Port _handlerPort;

	/* pointer to a new thread */
	SandtrayEventThread* _sandtrayEventThread;
   SandtrayEventController* _sandtrayEventController;
   SandtrayEventYarpInterface* _sandtrayEventYarpInterface;
public:
	/* class methods */
	bool configure(yarp::os::ResourceFinder &rf);
	bool interruptModule();
	bool close();
	bool respond(const yarp::os::Bottle& command, Bottle& reply);
	double getPeriod();
	bool updateModule();
};

#endif
