/** @file feedbackMessages.h
*
* Version 1.0
*
* Generated by YarpGenerator, Emmanuel Senft, PLYM
*
*
* \defgroup DREAM_cognitiveComponent sharedResources
*
* Header class to share sandtray messages between components
*
* \section lib_sec Libraries
*
* None
*
* \section in_files_sec Input Data Files
*
* None
*
* \section out_data_sec Output Data Files
*
* None
*
* \author
*
* <Emmanuel Senft>, <Plymouth University>
*
* Copyright (C) 2014 DREAM Consortium
*
*/

/*
* Copyright (C) 2014 DREAM Consortium
* FP7 Project 611391 co-funded by the European Commission
*
* Author:  Emmanuel Senft, Plymouth University
* Email:   emmanuel.senft@plymouth.ac.uk
* Website: www.dream2020.eu
*
* This program comes with ABSOLUTELY NO WARRANTY
*/

/*
* Audit Trail
* -----------
* 27/06/2016 Version 1.0: ... (Emmanuel Senft)
*/

#ifndef FEEDBACKMESSAGES
#define FEEDBACKMESSAGES

#include <string>

//int message, int step, int actionId`

/* ------------------------------- */
/*        MOTOR FEEDBACK           */
/* ------------------------------- */
const int _FEEDBACK_INCORRECT_DATA_ = 0;				
const int _FEEDBACK_SUCCESS_ = 1;						
const int _FEEDBACK_FAILURE_ = 2;						
const int _FEEDBACK_BEHAVIOUR_NOT_INSTALLED_ = 3;		
const int _FEEDBACK_IMPOSSIBLE_ = 4;	
const int _FEEDBACK_NOT_CONNECTED_ = 5;	

#endif