/** @file moveSequenceId.h
*
* Version 1.0
*
* Generated by YarpGenerator, Emmanuel Senft, PLYM
*
*
* \defgroup DREAM_cognitiveComponent sharedResources
*
* Header class to share sandtray messages between components
*
* \section lib_sec Libraries
*
* None
*
* \section in_files_sec Input Data Files
*
* None
*
* \section out_data_sec Output Data Files
*
* None
*
* \author
*
* <Emmanuel Senft>, <Plymouth University>
*
* Copyright (C) 2014 DREAM Consortium
*
*/

/*
* Copyright (C) 2014 DREAM Consortium
* FP7 Project 611391 co-funded by the European Commission
*
* Author:  Emmanuel Senft, Plymouth University
* Email:   emmanuel.senft@plymouth.ac.uk
* Website: www.dream2020.eu
*
* This program comes with ABSOLUTELY NO WARRANTY
*/

/*
* Audit Trail
* -----------
* 27/06/2016 Version 1.0: ... (Emmanuel Senft)
*/

#ifndef MOVESEQUENCEID
#define MOVESEQUENCEID

#include <string>
#include <vector>

/* -------------------------------------- */
/*        SENTENCES FOR REACTION          */
/* -------------------------------------- */

const std::string _fallingSpeech[] = {"Ouch", "Sorry, today I am a bit clumsy", "I am okay, do not worry", "Ups I just fell, but I am okay", "the floor is slippery today"};

const std::string _positiveSpeech[] = {"you are really nice", "that was great", "I am having fun today", "I like spending time with you", "I am glad we are playing together"};

const std::string _negativeSpeech[] = {"I did not like that", "that hurted a bit", "oooh", "please do not do that again", "I prefer to play another game"};


// List of ids of moveSequence behaviours

/* ---------------------------------------------------- */
/*       FLEXIBLE BEHAVIOUR TO LOAD FROM CONFIG 0-100   */
/* ---------------------------------------------------- */


/* ------------------------------- */
/*       HARD CODED BEHAVIOUR 	   */
/* ------------------------------- */
const int _MOVE_LIMIT_ = 100;
const int _MOVE_HAPPY_FACE_ = 101;
const int _MOVE_SAD_FACE_ = 102;
const int _MOVE_ANGRY_FACE_ = 103;
const int _MOVE_FEAR_FACE_ = 104;
const int _MOVE_NEUTRAL_FACE_ = 105;
const int _MOVE_MICRO_MOTIONS_ = 106;
const int _MOVE_STOP_MICRO_MOTIONS_ = 107;
const int _MOVE_BLINKING_ = 108;			//Expect 3 arguments: int repetitions (1/2/3), bool fullLeds, int duration milliseconds.
const int _MOVE_WAITING_GRAB_ = 109;	
const int _MOVE_WAITING_DROP_ = 110;
const int _MOVE_STAND_ = 111;

const int _MOVE_DAMAGE_AVOIDANCE_ = 201;
const int _MOVE_GET_UP_ = 202;
const int _MOVE_MICRO_EXPLAIN_3_ = 203;
const int _MOVE_MICRO_EXPLAIN_8_ = 204;
const int _MOVE_MICRO_THIS_ = 205;
const int _MOVE_MICRO_WHATSTHIS_2_ = 206;
const int _MOVE_MICRO_WHATSTHIS_5_ = 207;
const int _MOVE_MICRO_YOUKNOWWHAT_ = 208;
const int _MOVE_GOOD_FB_IMITATION_OBJECT_ =  209;
const int _MOVE_GOOD_FB_IMITATION_MOVE_ =  210;
#endif