/** @file naoMessages.h
*
* Version 1.0
*
* Generated by YarpGenerator, Emmanuel Senft, PLYM
*
*
* \defgroup DREAM_cognitiveComponent sharedResources
*
* Header class used to share messages between components
*
* \section lib_sec Libraries
*
* None
*
* \section in_files_sec Input Data Files
*
* None
*
* \section out_data_sec Output Data Files
*
* None
*
* \author
*
* <James Kennedy>, <Plymouth University>
*
* Copyright (C) 2014 DREAM Consortium
*
*/

/*
* Copyright (C) 2014 DREAM Consortium
* FP7 Project 611391 co-funded by the European Commission
*
* Author:  James Kennedy, Plymouth University
* Email:   james.kennedy@plymouth.ac.uk
* Website: www.dream2020.eu
*
* This program comes with ABSOLUTELY NO WARRANTY
*/

/*
* Audit Trail
* -----------
* 27/06/2016 Version 1.0: ... (James Kennedy)
*/

#ifndef NAOMESSAGES
#define NAOMESSAGES

/* ------------------------------- */
/*        NAO BEHAVIOURS        */
/* ------------------------------- */
const int _EXAMPLE_BEHAVIOUR_ = 1;						// call behaviour named 'Example1'

/* --------------------------------	*/
/*        ANGLE INTERPOLATIONS			*/
/* --------------------------------	*/
const int _EXAMPLE_INTERPOLATION_ = 101;	// see code in dropbox - filename movement1-simplified.txt


#endif