/** @file PERFORMANCEMESSAGES.h
*
* Version 1.0
*
* Generated by YarpGenerator, Emmanuel Senft, PLYM
*
*
* \defgroup DREAM_cognitiveComponent sharedResources
*
* Header class to share sandtray messages between components
*
* \section lib_sec Libraries
*
* None
*
* \section in_files_sec Input Data Files
*
* None
*
* \section out_data_sec Output Data Files
*
* None
*
* \author
*
* <James Kennedy>, <Plymouth University>
*
* Copyright (C) 2014 DREAM Consortium
*
*/

/*
* Copyright (C) 2014 DREAM Consortium
* FP7 Project 611391 co-funded by the European Commission
*
* Author:  James Kennedy, Plymouth University
* Email:   James.Kennedy@plymouth.ac.uk
* Website: www.dream2020.eu
*
* This program comes with ABSOLUTELY NO WARRANTY
*/

/*
* Audit Trail
* -----------
* 27/06/2016 Version 1.0: ... (James Kennedy)
*/

#ifndef PERFORMANCEMESSAGES
#define PERFORMANCEMESSAGES

#include <string>

// performance expected (from getInterventionStatus)
const int _PERF_NO_CHECK_ = -1;
const int _PERF_NO_BEHAVIOUR_ = 0;
const int _PERF_SANDTRAY_GOOD_ = 1;
const int _PERF_SANDTRAY_TOUCH_ = 2;
const int _PERF_SANDTRAY_NO_TOUCH_ = 3;
const int _PERF_TOUCH_ROBOT_OWNED_ = 4;
const int _PERF_LOOK_RIGHT_ = 5;
const int _PERF_LOOK_LEFT_ = 6;
const int _PERF_POINT_LEFT_ = 7;
const int _PERF_POINT_RIGHT_ = 8;
const int _PERF_NO_MOVEMENT_ = 9;
const int _PERF_SPEAK_ = 10;
const int _PERF_WAVE_ = 11;
const int _PERF_COVER_ = 12;
const int _PERF_HANDS_ON_HEAD_ = 13;
const int _PERF_FLY_ = 14;
const int _PERF_DRIVE_ = 15;
const int _PERF_DRINK_SMELL_ = 16;
const int _PERF_TRAJ_1_ = 17;
const int _PERF_TRAJ_2_ = 18;
const int _PERF_TRAJ_3_ = 19;
const int _PERF_TRAJ_4_ = 20;
const int _PERF_KNOCKING_ = 21;
// <11 = motions

// performance we are checking for (and result value)
const int _PERF_CHECK_LOOK_LEFT_ = 0;
const int _PERF_CHECK_LOOK_RIGHT_ = 1;
const int _PERF_CHECK_POINT_LEFT_ = 0;
const int _PERF_CHECK_POINT_RIGHT_ = 1;
const int _PERF_CHECK_NO_MOVEMENT_ = 2;
const int _PERF_CHECK_CHILD_SPEAKS_ = 1;

// sandtray event ids
const int _PERF_SANDTRAY_CHECK_GOOD_ = 0;
const int _PERF_SANDTRAY_CHECK_BAD_ = 1;
const int _PERF_SANDTRAY_CHECK_TOUCH_ = 3;
const int _PERF_SANDTRAY_CHECK_TOUCH_OWNED_ = 4;

// performance outcome
const int _PERF_NONE_ = -1;
const int _PERF_BAD_ = 0;
const int _PERF_GOOD_ = 1;

// timing
const int _PERF_OUT_OF_TIME_ = 0;
const int _PERF_ON_TIME_ = 1;

// for knowing if we have head
const double _PERF_NO_HEAD_ = -9999;

// sandtray bounding boxes
const double _PERF_SAND_Z1_ = 200;
const double _PERF_SAND_Z2_ = 700;
const double _PERF_SAND_X1_ = 100;
const double _PERF_SAND_X2_ = 550;

#endif