 /** @file naoInterfaceDriverYarpInterface.h 
  *
  * Version 1.0
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  *
  * \defgroup DREAM_cognitiveComponent naoInterfaceDriver
  * 
  * Class used to provided a simpler interface between the main code and the YARP layer.
  * Provide an output function sending data for each port, and an input function called 
  * when a message is received on a port.
  * 
  * \section lib_sec Libraries
  *
  * - YARP.
  *
  * \section portsc_sec Ports Created
  *
  * <b>Port types </b>
  *
  *	BufferedPort<Bottle>		sensorFeedbackIn;
  *	BufferedPort<Bottle>		robotMotorFeedbackIn;
  *	BufferedPort<VectorOf<int>>		disableRobotOut;
  *	BufferedPort<VectorOf<int>>		enableRobotOut;
  *	BufferedPort<VectorOf<int>>		gripOut;
  *	BufferedPort<VectorOf<double>>		moveHandOut;
  *	BufferedPort<VectorOf<double>>		moveTorsoOut;
  *	BufferedPort<VectorOf<int>>		releaseOut;
  *	BufferedPort<Bottle>		sayOut;
  *	BufferedPort<VectorOf<int>>		moveSequenceOut;
  *	BufferedPort<VectorOf<double>>		moveHeadOut;
  *	BufferedPort<VectorOf<float>>		pointAtOut;
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \author 
  * 
  * <Emmanuel Senft>, <PLYM>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */

/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  Emmanuel Senft, PLYM 
 * Email:   emmanuel.senft@plymouth.ac.uk 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */

 
 /* 
  * Audit Trail
  * -----------
  * 16/08/2016 Version 1.0: ... (Emmanuel Senft)
  */ 
 
#ifndef NAOINTERFACEDRIVERYARPINTERFACE
#define NAOINTERFACEDRIVERYARPINTERFACE

#include <iostream>
#include <string>
#include <vector>

#include <yarp/sig/all.h>
#include <yarp/os/all.h>
#include <yarp/os/RFModule.h>
#include <yarp/os/Network.h>
#include <yarp/os/Thread.h>

using namespace yarp::os; 
using namespace yarp::sig;

class NaoInterfaceDriverThread;
class NaoInterfaceDriverController;

class NaoInterfaceDriverYarpInterface{
private:
	NaoInterfaceDriverThread* _yarpThread;
    NaoInterfaceDriverController* _controller;
public:
	/* class methods */
	NaoInterfaceDriverYarpInterface();
    void init(NaoInterfaceDriverThread* yarpThread, NaoInterfaceDriverController* controller);
	void getFromSensorFeedback(Bottle data);
	void getFromRobotMotorFeedback(Bottle data);
	void sendToDisableRobot(int stepId);
	void sendToEnableRobot(int stepId);
	void sendToGrip(bool rightHand, int stepId);
	void sendToMoveHand(std::vector<double> data, int stepId);
	void sendToMoveTorso(std::vector<double> data, int stepId);
	void sendToRelease(bool rightHand, int stepId);
	void sendToSay(std::string sentence, int stepId);
	void sendToMoveSequence(int stepId, int actionId);
	void sendToMoveSequence(int stepId, int actionId, int repetitions, int fullLed, int duration);
	void sendToMoveHead(std::vector<double> values, int stepId);
	void sendToPointAt(std::vector<float> values, int stepId);
};

#endif
