 /** @file wp5StubYarpInterface.h 
  *
  * Version 1.0
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  *
  * \defgroup DREAM_cognitiveComponent wp5Stub
  * 
  * Class used to provided a simpler interface between the main code and the YARP layer.
  * Provide an output function sending data for each port, and an input function called 
  * when a message is received on a port.
  * 
  * \section lib_sec Libraries
  *
  * - YARP.
  *
  * \section portsc_sec Ports Created
  *
  * <b>Port types </b>
  *
  *	BufferedPort<VectorOf<int>>		getInterventionStatusIn;
  *	BufferedPort<VectorOf<int>>		interactionEventIn;
  *	BufferedPort<VectorOf<double>>		getBodyIn;
  *	BufferedPort<VectorOf<double>>		getBodyPoseIn;
  *	BufferedPort<VectorOf<double>>		getEyeGazeIn;
  *	BufferedPort<VectorOf<double>>		identifyTrajectoryIn;
  *	BufferedPort<VectorOf<int>>		identifyVoiceIn;
  *	BufferedPort<VectorOf<double>>		identifyFaceExpressionIn;
  *	BufferedPort<VectorOf<int>>		checkMutualGazeIn;
  *	BufferedPort<VectorOf<double>>		engagementFlagOut;
  *	BufferedPort<VectorOf<double>>		getChildBehaviourOut;
  *	BufferedPort<VectorOf<double>>		getChildPerformanceOut;
  *	BufferedPort<VectorOf<int>>		identifyTrajectoryOut;
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \author 
  * 
  * <Emmanuel Senft>, <Plymouth University>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */

/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  Emmanuel Senft, Plymouth University 
 * Email:   emmanuel.senft@plymouth.ac.uk 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */

 
 /* 
  * Audit Trail
  * -----------
  * 20/09/2016 Version 1.0: ... (Emmanuel Senft)
  */ 
 
#ifndef WP5STUBYARPINTERFACE
#define WP5STUBYARPINTERFACE

#include <iostream>
#include <string>
#include <vector>

#include <yarp/sig/all.h>
#include <yarp/os/all.h>
#include <yarp/os/RFModule.h>
#include <yarp/os/Network.h>
#include <yarp/os/Thread.h>

using namespace yarp::os; 
using namespace yarp::sig;

class Wp5StubThread;
class Wp5StubController;

class Wp5StubYarpInterface{
private:
	Wp5StubThread* _yarpThread;
   Wp5StubController* _controller;
   int _expectedBehav;
   bool _bSpamOn;
public:
	/* class methods */
	Wp5StubYarpInterface();
   void init(Wp5StubThread* yarpThread, Wp5StubController* controller);
	void getFromGetInterventionStatus(VectorOf<int> data);
	void getFromInteractionEvent(VectorOf<int> data);
	void getFromGetBody(VectorOf<double> data);
	void getFromGetBodyPose(VectorOf<double> data);
	void getFromGetEyeGaze(VectorOf<double> data);
	void getFromIdentifyTrajectory(VectorOf<double> data);
	void getFromIdentifyVoice(VectorOf<int> data);
	void getFromIdentifyFaceExpression(VectorOf<double> data);
	void getFromCheckMutualGaze(VectorOf<int> data);
	void sendToEngagementFlag(VectorOf<double> data);
    int randi(int lo, int hi);
	void sendToGetChildBehaviour(VectorOf<double> data);
	void sendToGetChildPerformance(float perf);
	void sendToIdentifyTrajectory(VectorOf<int> data);
};

#endif
