 /** @file wp5Stub.h 
  *
  * Version 1.0
  * 
  * 20/09/2016
  * 
  * Generated by YarpGenerator, Emmanuel Senft, PLYM
  *
  * \section component_description Component Description
  *
  * Functionally, the component  does ...xyz...
  * 
  * \section lib_sec Libraries
  *
  * - YARP.
  *
  * \section parameters_sec Parameters
  * 
  * <b>Command-line Parameters </b> 
  * 
  * The following key-value pairs can be specified as command-line parameters 
  * by prefixing \c -- to the key e.g. \c --from file.ini. 
  * The value part can be changed to suit your needs; the default values are 
  * shown below. 
  *
  * - \c from \c wp5Stub.ini 
  *    - specifies the configuration file
  *
  * - \c context \c component/wp5Stub/configuration
  *   - specifies the sub-path from \c $DREAM_ROOT/release
  *   to the configuration file
  *
  * - \c name \c wp5Stub   
  *   - specifies the name of the component (used to form the stem of component port names)  
  *
  *
  * <b>Configuration File Parameters </b>
  *
  * The following key-value pairs can be specified as parameters in the configuration file 
  * (they can also be specified as command-line parameters if you so wish). 
  * The value part can be changed to suit your needs; the default values are shown below. 
  * 
  * Key | Value
  * :-- | :----  
  * _getInterventionStatusIn | /wp5Stub/getInterventionStatus:i
  * _interactionEventIn | /wp5Stub/interactionEvent:i
  * _getBodyIn | /wp5Stub/getBody:i
  * _getBodyPoseIn | /wp5Stub/getBodyPose:i
  * _getEyeGazeIn | /wp5Stub/getEyeGaze:i
  * _identifyTrajectoryIn | /wp5Stub/identifyTrajectory:i
  * _identifyVoiceIn | /wp5Stub/identifyVoice:i
  * _identifyFaceExpressionIn | /wp5Stub/identifyFaceExpression:i
  * _checkMutualGazeIn | /wp5Stub/checkMutualGaze:i
  *
  * - description
  *   
  * Key | Value
  * :-- | :---- 
  * _engagementFlagOut | /wp5Stub/engagementFlag:o    
  * _getChildBehaviourOut | /wp5Stub/getChildBehaviour:o    
  * _getChildPerformanceOut | /wp5Stub/getChildPerformance:o    
  * _identifyTrajectoryOut | /wp5Stub/identifyTrajectory:o    
  *
  * - description
  *
  * \section portsa_sec Ports Accessed
  * 
  * - None
  *                      
  * \section portsc_sec Ports Created
  *
  * <b>Input ports</b>
  *
  *  - \c /wp5Stub
  *
  *  - \c /wp5Stub/getInterventionStatus:i
  *  - \c /wp5Stub/interactionEvent:i
  *  - \c /wp5Stub/getBody:i
  *  - \c /wp5Stub/getBodyPose:i
  *  - \c /wp5Stub/getEyeGaze:i
  *  - \c /wp5Stub/identifyTrajectory:i
  *  - \c /wp5Stub/identifyVoice:i
  *  - \c /wp5Stub/identifyFaceExpression:i
  *  - \c /wp5Stub/checkMutualGaze:i
  *
  * <b>Output ports</b>
  *
  *  - \c /wp5Stub
  *
  *  - \c /wp5Stub/engagementFlag:o
  *  - \c /wp5Stub/getChildBehaviour:o
  *  - \c /wp5Stub/getChildPerformance:o
  *  - \c /wp5Stub/identifyTrajectory:o
  *
  * <b>Port types </b>
  *
  * The functional specification only names the ports to be used to communicate with the component 
  * but doesn't say anything about the data transmitted on the ports. This is defined by the following code. 
  *
  * \c BufferedPort<VectorOf<int>>		getInterventionStatusIn; 
  * \c BufferedPort<VectorOf<int>>		interactionEventIn; 
  * \c BufferedPort<VectorOf<double>>		getBodyIn; 
  * \c BufferedPort<VectorOf<double>>		getBodyPoseIn; 
  * \c BufferedPort<VectorOf<double>>		getEyeGazeIn; 
  * \c BufferedPort<VectorOf<double>>		identifyTrajectoryIn; 
  * \c BufferedPort<VectorOf<int>>		identifyVoiceIn; 
  * \c BufferedPort<VectorOf<double>>		identifyFaceExpressionIn; 
  * \c BufferedPort<VectorOf<int>>		checkMutualGazeIn; 
  * \c BufferedPort<VectorOf<double>>		engagementFlagOut; 
  * \c BufferedPort<VectorOf<double>>		getChildBehaviourOut; 
  * \c BufferedPort<VectorOf<double>>		getChildPerformanceOut; 
  * \c BufferedPort<VectorOf<int>>		identifyTrajectoryOut; 
  *
  * \section in_files_sec Input Data Files
  *
  * None
  *
  * \section out_data_sec Output Data Files
  *
  * None
  *
  * \section conf_file_sec Configuration Files
  *
  * \c wp5Stub.ini   
  *
  * \section example_sec Example Instantiation of the Component
  * 
  * <tt>wp5Stub --name wp5Stub --context wp5Stub/config --from wp5Stub.ini </tt>
  *
  * \author 
  * 
  * <Emmanuel Senft>, <Plymouth University>  
  * 
  * Copyright (C) 2014 DREAM Consortium
  * 
  */
  
/* 
 * Copyright (C) 2014 DREAM Consortium
 * FP7 Project 611391 co-funded by the European Commission
 *
 * Author:  Emmanuel Senft, Plymouth University 
 * Email:   emmanuel.senft@plymouth.ac.uk 
 * Website: www.dream2020.eu 
 * 
 * This file is part of DREAM.
 * 
 * DREAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DREAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DREAM.  If not, see <http://www.gnu.org/licenses/>.
 */

  
 /* 
  * Audit Trail
  * -----------
  * 20/09/2016 Version 1.0: ... (Emmanuel Senft)
  */ 
 
#ifndef WP5STUB
#define WP5STUB

#include <iostream>
#include <string>
#include <vector>

#include <yarp/sig/all.h>
#include <yarp/os/all.h>
#include <yarp/os/RFModule.h>
#include <yarp/os/Network.h>
#include <yarp/os/Thread.h>

using namespace yarp::os; 
using namespace yarp::sig;

class Wp5StubYarpInterface;
class Wp5StubController;

class GetInterventionStatusInAnalyser : public BufferedPort<VectorOf<int>>{
   virtual void onRead(VectorOf<int>& getInterventionStatusInData);
   Wp5StubYarpInterface *_wp5StubYarpInterface;
public:
   void setWp5Stub(Wp5StubYarpInterface* yarpInterface);
};

class InteractionEventInAnalyser : public BufferedPort<VectorOf<int>>{
   virtual void onRead(VectorOf<int>& interactionEventInData);
   Wp5StubYarpInterface *_wp5StubYarpInterface;
public:
   void setWp5Stub(Wp5StubYarpInterface* yarpInterface);
};

class GetBodyInAnalyser : public BufferedPort<VectorOf<double>>{
   virtual void onRead(VectorOf<double>& getBodyInData);
   Wp5StubYarpInterface *_wp5StubYarpInterface;
public:
   void setWp5Stub(Wp5StubYarpInterface* yarpInterface);
};

class GetBodyPoseInAnalyser : public BufferedPort<VectorOf<double>>{
   virtual void onRead(VectorOf<double>& getBodyPoseInData);
   Wp5StubYarpInterface *_wp5StubYarpInterface;
public:
   void setWp5Stub(Wp5StubYarpInterface* yarpInterface);
};

class GetEyeGazeInAnalyser : public BufferedPort<VectorOf<double>>{
   virtual void onRead(VectorOf<double>& getEyeGazeInData);
   Wp5StubYarpInterface *_wp5StubYarpInterface;
public:
   void setWp5Stub(Wp5StubYarpInterface* yarpInterface);
};

class IdentifyTrajectoryInAnalyser : public BufferedPort<VectorOf<double>>{
   virtual void onRead(VectorOf<double>& identifyTrajectoryInData);
   Wp5StubYarpInterface *_wp5StubYarpInterface;
public:
   void setWp5Stub(Wp5StubYarpInterface* yarpInterface);
};

class IdentifyVoiceInAnalyser : public BufferedPort<VectorOf<int>>{
   virtual void onRead(VectorOf<int>& identifyVoiceInData);
   Wp5StubYarpInterface *_wp5StubYarpInterface;
public:
   void setWp5Stub(Wp5StubYarpInterface* yarpInterface);
};

class IdentifyFaceExpressionInAnalyser : public BufferedPort<VectorOf<double>>{
   virtual void onRead(VectorOf<double>& identifyFaceExpressionInData);
   Wp5StubYarpInterface *_wp5StubYarpInterface;
public:
   void setWp5Stub(Wp5StubYarpInterface* yarpInterface);
};

class CheckMutualGazeInAnalyser : public BufferedPort<VectorOf<int>>{
   virtual void onRead(VectorOf<int>& checkMutualGazeInData);
   Wp5StubYarpInterface *_wp5StubYarpInterface;
public:
   void setWp5Stub(Wp5StubYarpInterface* yarpInterface);
};



class Wp5StubThread : public yarp::os::Thread{
private:
	/* class variables */
	yarp::os::BufferedPort<VectorOf<int>>* _getInterventionStatusIn;
	yarp::os::BufferedPort<VectorOf<int>>* _interactionEventIn;
	yarp::os::BufferedPort<VectorOf<double>>* _getBodyIn;
	yarp::os::BufferedPort<VectorOf<double>>* _getBodyPoseIn;
	yarp::os::BufferedPort<VectorOf<double>>* _getEyeGazeIn;
	yarp::os::BufferedPort<VectorOf<double>>* _identifyTrajectoryIn;
	yarp::os::BufferedPort<VectorOf<int>>* _identifyVoiceIn;
	yarp::os::BufferedPort<VectorOf<double>>* _identifyFaceExpressionIn;
	yarp::os::BufferedPort<VectorOf<int>>* _checkMutualGazeIn;
	yarp::os::BufferedPort<VectorOf<double>>* _engagementFlagOut;
	yarp::os::BufferedPort<VectorOf<double>>* _getChildBehaviourOut;
	yarp::os::BufferedPort<VectorOf<double>>* _getChildPerformanceOut;
	yarp::os::BufferedPort<VectorOf<int>>* _identifyTrajectoryOut;
	Wp5StubYarpInterface* _yarpInterface;
	GetInterventionStatusInAnalyser *_getInterventionStatusInAnalyser;
	InteractionEventInAnalyser *_interactionEventInAnalyser;
	GetBodyInAnalyser *_getBodyInAnalyser;
	GetBodyPoseInAnalyser *_getBodyPoseInAnalyser;
	GetEyeGazeInAnalyser *_getEyeGazeInAnalyser;
	IdentifyTrajectoryInAnalyser *_identifyTrajectoryInAnalyser;
	IdentifyVoiceInAnalyser *_identifyVoiceInAnalyser;
	IdentifyFaceExpressionInAnalyser *_identifyFaceExpressionInAnalyser;
	CheckMutualGazeInAnalyser *_checkMutualGazeInAnalyser;
	
public:
	/* class methods */
	Wp5StubThread(BufferedPort<VectorOf<int>>* getInterventionStatusIn, BufferedPort<VectorOf<int>>* interactionEventIn, BufferedPort<VectorOf<double>>* getBodyIn, BufferedPort<VectorOf<double>>* getBodyPoseIn, BufferedPort<VectorOf<double>>* getEyeGazeIn, BufferedPort<VectorOf<double>>* identifyTrajectoryIn, BufferedPort<VectorOf<int>>* identifyVoiceIn, BufferedPort<VectorOf<double>>* identifyFaceExpressionIn, BufferedPort<VectorOf<int>>* checkMutualGazeIn, BufferedPort<VectorOf<double>>* engagementFlagOut, BufferedPort<VectorOf<double>>* getChildBehaviourOut, BufferedPort<VectorOf<double>>* getChildPerformanceOut, BufferedPort<VectorOf<int>>* identifyTrajectoryOut);
   void setYarpInterface(Wp5StubYarpInterface* yarpInterface);
	bool threadInit();
	void threadRelease();
	void sendToEngagementFlag(VectorOf<double> data);
	void sendToGetChildBehaviour(VectorOf<double> data);
	void sendToGetChildPerformance(VectorOf<double> data);
	void sendToIdentifyTrajectory(VectorOf<int> data);
	void run();
};

class Wp5Stub : public yarp::os::RFModule{
private:
	/* module parameters */
	std::string _moduleName;
	std::string _getInterventionStatusInName;
	std::string _interactionEventInName;
	std::string _getBodyInName;
	std::string _getBodyPoseInName;
	std::string _getEyeGazeInName;
	std::string _identifyTrajectoryInName;
	std::string _identifyVoiceInName;
	std::string _identifyFaceExpressionInName;
	std::string _checkMutualGazeInName;
	std::string _engagementFlagOutName;
	std::string _getChildBehaviourOutName;
	std::string _getChildPerformanceOutName;
	std::string _identifyTrajectoryOutName;
	std::string _handlerPortName;

	/* class variables */
	yarp::os::BufferedPort<VectorOf<int>> _getInterventionStatusIn;
	yarp::os::BufferedPort<VectorOf<int>> _interactionEventIn;
	yarp::os::BufferedPort<VectorOf<double>> _getBodyIn;
	yarp::os::BufferedPort<VectorOf<double>> _getBodyPoseIn;
	yarp::os::BufferedPort<VectorOf<double>> _getEyeGazeIn;
	yarp::os::BufferedPort<VectorOf<double>> _identifyTrajectoryIn;
	yarp::os::BufferedPort<VectorOf<int>> _identifyVoiceIn;
	yarp::os::BufferedPort<VectorOf<double>> _identifyFaceExpressionIn;
	yarp::os::BufferedPort<VectorOf<int>> _checkMutualGazeIn;
	yarp::os::BufferedPort<VectorOf<double>> _engagementFlagOut;
	yarp::os::BufferedPort<VectorOf<double>> _getChildBehaviourOut;
	yarp::os::BufferedPort<VectorOf<double>> _getChildPerformanceOut;
	yarp::os::BufferedPort<VectorOf<int>> _identifyTrajectoryOut;
	yarp::os::Port _handlerPort;

	/* pointer to a new thread */
	Wp5StubThread* _wp5StubThread;
   Wp5StubController* _wp5StubController;
   Wp5StubYarpInterface* _wp5StubYarpInterface;
public:
	/* class methods */
	bool configure(yarp::os::ResourceFinder &rf);
	bool interruptModule();
	bool close();
	bool respond(const yarp::os::Bottle& command, Bottle& reply);
	double getPeriod();
	bool updateModule();
};

#endif
